program: nl_sweep_yaml.py
method: grid
name: reaAct_sweep_CIFAR10_resnet50_SGD
metric:
  goal: minimize
  name: val_loss

parameters:
  architecture:
    value: "resnet50"
  dataset:
    value: "CIFAR10"
  lr:
    values: [0.01, 0.001]
  activation:
    values: ["sampling", "relu"]
  optimizer: 
    value: "SGD"
  momentum:
    values: [0, 0.1, 0.5, 0.9]
  batch_size:
    value: 256
  num_workers:
    value: 24
  lr_scheduler:
    values: [True, False]
  epochs:
    value: 200
  